In [1]:

import numpy as np

# 3개 지점, 6개 상품의 재고 수량
stock = np.array([
    [12,  5, 18,  7, 10, 15],
    [ 8, 14, 11,  9,  6, 13],
    [16, 10,  9, 12, 14,  8]
])

# 상품 코드
product_ids = np.array([101, 102, 103, 104, 105, 106])

stock
     

array([[12,  5, 18,  7, 10, 15],
       [ 8, 14, 11,  9,  6, 13],
       [16, 10,  9, 12, 14,  8]])

# 1. 정렬
product_ids를 오름차순 정렬하시오.
첫 번째 지점 재고를 오름차순 정렬하시오.
stock를 행 기준으로 정렬하시오.

In [ ]:
print(np.sort(product_ids))
print(np.sort([product_ids[0,:]]))
print(np.sort(product_ids,axis=0))

[101 102 103 104 105 106]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# 2. 역순 정렬
두 번째 지점 재고를 내림차순으로 정렬하시오.

In [5]:
print(np.sort(product_ids)[-1,:])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# 3. argsort
세 번째 지점 재고를 많이 가진 상품 순서의 인덱스를 구하시오. 그리고 그 인덱스를 이용해 상품 코드도 같은 순서로 정렬하시오.

In [15]:
indices = np.argsort(stock[2])[::-1]
print(indices)
print(product_ids[indices])

[0 4 3 1 2 5]
[101 105 104 102 103 106]


# 4. insert
첫 번째 지점 재고 앞에 신상품 재고 20을 삽입한 1차원 배열을 만드시오.

In [ ]:
np.insert(stock[0],0,20)

[[20 20 20 20 20 20]
 [12  5 18  7 10 15]
 [ 8 14 11  9  6 13]
 [16 10  9 12 14  8]]


# 5. delete
stock에서 마지막 상품 열을 삭제하시오.
stock에서 두 번째 지점 행을 삭제하시오.

In [ ]:
print(np.delete(stock,-1,axis=1))
print(np.delete(stock,1, axis=0))


[[12  5 18  7 10]
 [ 8 14 11  9  6]
 [16 10  9 12 14]]
[[12  5 18  7 10 15]
 [16 10  9 12 14  8]]



# 6. append / concatenate
아래 online_stock을 stock 뒤에 세로로 붙인 result_append를 만드시오.

In [12]:
online_stock = np.array([[20, 18, 15, 10, 12, 17]])
result_append=np.vstack((stock,online_stock))
print(result_append)

[[12  5 18  7 10 15]
 [ 8 14 11  9  6 13]
 [16 10  9 12 14  8]
 [20 18 15 10 12 17]]


# 7. vstack / hstack
stock 아래에 warehouse_stock을 세로로 붙이시오.
stock 오른쪽에 event_stock을 가로로 붙이시오.

In [13]:
warehouse_stock = np.array([[30, 25, 28, 20, 26, 22]])
event_stock = np.array([[1], [2], [3]])

print(np.vstack((stock,warehouse_stock)))
print(np.hstack((stock,event_stock)))

[[12  5 18  7 10 15]
 [ 8 14 11  9  6 13]
 [16 10  9 12 14  8]
 [30 25 28 20 26 22]]
[[12  5 18  7 10 15  1]
 [ 8 14 11  9  6 13  2]
 [16 10  9 12 14  8  3]]


# 8. split
product_ids를 3개씩 나누시오. 그리고 stock를 열 기준으로 2개 블록으로 나누시오.

In [14]:
print(np.vsplit(product_ids,3))
print(np.hsplit(stock,2))

ValueError: vsplit only works on arrays of 2 or more dimensions