# 통계 기초
NumPy 통계는 정식 통계분석 도구라기보다, 데이터를 빠르게 요약하고 분포를 감 잡기 위한 기초 연산이다.

In [1]:
import numpy as np

## 중심 경향 축도 (central Tendency)
데이터의 대표적인 중심 값을 나타내는 통계 지표이다.
대표적으로 다음 세가지를 많이 사용한다.
- 평균(mean) : 모든 값의 합을 데이터 개수로 나눈 값
- 중앙값(median) : 데이터를 정렬했을 때 가운데 위치한 값
- 최빈값(mode) : 가장 많이 등장하는 값

In [2]:
# 학생들의 시험점수
scores = np.array([85, 90, 92, 88, 90, 75, 88, 95, 92, 85, 80, 95, 100, 92, 85])

In [4]:
# 평균(Mean) : 데이터의 전체적인 중심을 나타내는 가장 기본적인 통계값
print(f'합계:{np.sum(scores)}')
print(f'데이터 개수:{scores.size}')
print(f'평균:{np.mean(scores)}')

합계:1332
데이터 개수:15
평균:88.8


In [6]:
# 중앙값(Median): 데이터를 정렬했을 때 가운데 위치한 값
# 홀수 -> 가운데 1개 값
# 짝수 -> 가운데 2개 값 평균
# 이상치(out;ier)의 영향을 평균보다 덜 받는 특징
print(sorted(scores))
print(f'중앙값 : {np.median(scores)}')

[np.int64(75), np.int64(80), np.int64(85), np.int64(85), np.int64(85), np.int64(88), np.int64(88), np.int64(90), np.int64(90), np.int64(92), np.int64(92), np.int64(92), np.int64(95), np.int64(95), np.int64(100)]
중앙값 : 90.0


In [ ]:
# 최빈값(Mode) : 데이터에서 가장 많이 등장하는 값
print(f'중복 제거한 값: {np.unique(scores)}')
values, counts = np.unique(scores, return_counts=True)
print(values, counts)

max_count = np.max(counts)
# 최대 빈도수와 같은 위치의 값만 선택
vals= values[counts == max_count]
print(f"최빈값: {vals}, 빈도수: {max_count}")

## 산포 측도
데이터가 평균을 기준으로 얼마나 퍼져 있는지를 나타내는 지표이다.
대표적으로 다음 두가지를 많이 사용한다.
- 분산(variance)
- 표준편차(standard deviation)

In [8]:
# 분산 : 데이터가 평균에서 얼마나 떨어져있는지 나타내는 값
# 값이 클수록 데이터의 퍼짐 정도가 크다는 의미
# (값-평균) ^2의 평균
print(f"분산: {np.mean((scores - np.mean(scores)) ** 2)}")
print(f"분산: {np.var(scores)}")

분산: 36.559999999999995
분산: 36.559999999999995


In [ ]:
# 표준편차 : 분산의 제곱급
# 데이터가 평균에서 얼마나 퍼져 있는지를 직관적으로 나타냄
print(f'표준편차: {np.sqrt(np.var(scores))}')
print(f'표준편차: {np.std(scores)}')

표준편차: 6.046486583132389
표준편차: 6.046486583132389


## 모집단 vs 표본
분산과 표준편차는 계산 방식에 따라 두 가지가 있다.
- 모집단 : 전체 데이터를 알고 있을 때
- 표본 : 일부 데이터로 전체를 추정할 때

Numpy에서는 ddof 옵션으로 구분한다. (분산 계산 시 나누는 값을 조정)
- ddof=0: 모집단(default)
- ddof=1: 표본

In [ ]:
# 모집단 기준 계산
print(f'모집단 분산: {np.var(scores, ddof=0)}')
print(f'모집단 표준편차: {np.std(scores, ddof=0)}')
# 표준 기준 계산 (분산 계산 시 나누는 값을 n-1로 처리하므로 값이 약간 더 크게 나온다)
print(f'표본 분산: {np.var(scores, ddof=1)}')
print(f'표본 표준편차: {np.std(scores, ddof=1)}')

모집단 분산: 36.559999999999995
모집단 표준편차: 6.046486583132389
표본 분산: 39.17142857142857
표본 표준편차: 6.258708219067939


## 자주 사용하는 기본 통계 함수
Numpy는 데이터 기본적인 통계 정보를 빠르게 확인할 수 있는 함수를 제공한다.
이 함수들은 데이터 탐색(EDA)이나 간단한 통계 확인에서 자주 사용 된다.

In [ ]:
# 예시 데이터
values = np.array([12,25,8,45,33,17,29,41])

# 합계, 최대, 최소
print(np.sum(values))
print(np.min(values))
print(np.max(values))

# 최대값, 최소값의 위치  (인덱스 반환)
print(np.argmin(values))
print(np.argmax(values))

# 범위 : 데이터의 전체 퍼짐 정도  (max - min)
print(np.ptp(values))

210
8
45
2
3


## 난수 생성 (Random Data)
Numpy는 다양한 확률 분포 기반의 난수 생성 함수를 제공한다.
대표적으로 다음 분포를 많이 사용한다.
- 정규분포(normal distribution)
- 균등분포(uniform distribution)

데이터 시뮬레이션이나 테스트 데이터 생성에 사용된다.

### 정규 분포
평균을 중심으로 좌우 대칭인 종 모양 분포이다.
Numpy에서는  np.random.normal() 함수로 생성한다.

In [13]:
# random.normal(loc, scale, size)
# loc 평균값, scale 표준편차, size 개수
arr = np.random.normal(0,1,100)
arr

array([ 1.32636341, -0.63759271,  0.1365899 , -1.13020807, -1.03569092,
        1.33543408, -0.86388773, -0.12523095, -1.92598991,  0.08559884,
       -0.83076847, -1.0870179 , -1.04984487, -0.20866757, -0.04494797,
        0.46029504,  3.67315704, -0.68132817,  0.25136646,  0.72297119,
        0.29736912, -0.22270574,  1.11981213, -0.39794311, -0.37738623,
        1.89397467,  0.03579105, -0.53303927, -0.6124056 , -0.19634601,
        0.95167907, -0.12237968,  0.06576056,  1.76339769, -0.371656  ,
        0.65769145,  1.38053643, -1.12926739,  0.11828796,  1.40751566,
        1.7048517 , -0.19510543,  0.77278125, -0.22822282,  0.30507885,
        1.13966513,  0.58566922,  0.75352484,  0.71635581, -0.29863967,
        0.74998949,  1.58822499,  0.07275082,  0.24491399, -0.66350842,
       -0.38900325, -1.012675  ,  0.11708845, -0.54031362, -0.3607308 ,
       -0.75612836, -1.14177583,  0.92473926, -0.05443854,  0.09993175,
       -0.95852938, -0.64885098, -0.53738195,  1.10600114, -0.83

### 표준 정규 분포
np.random.randn()은 평균 0, 표준편차 1의 정규분포 데이터를 생성한다.

In [ ]:
arr = np.random.randn(100)
arr = np.random.randn(5,20)
arr

<bound method RandomState.randn of RandomState(MT19937) at 0x24A7A54D940>

## 균등 분포
모든 값이 동일한 확률로 발생하는 분포이다.
np.random.randint() : 지정한 범위에서 정수 난수를 생성한다.

In [15]:
# random.randint(low, high, size)
# low-high 범위의 size 개수 균등 분포 반환
arr = np.random.randint(1,100,1000)
arr

array([15, 29, 36, 49, 59, 98, 81, 25, 47, 49, 76, 59,  9,  7, 37, 89, 67,
       79, 76, 51, 49, 48, 60, 88, 24, 99, 96, 38, 24, 47, 34, 30,  4, 81,
       58, 14, 28, 54, 32, 81, 23, 97, 75, 63, 29, 91, 31, 45, 70, 26, 94,
        8, 35, 67, 81, 94, 55, 48, 49, 69, 81, 90, 61, 93, 95, 31, 58, 49,
       34, 22, 86, 25, 48, 80,  9, 23, 60, 18, 49, 69, 77, 73, 69, 77, 35,
       26, 12, 17, 11, 66, 86, 32, 21,  9, 72, 24, 47, 28, 36, 36, 90, 52,
       40, 84, 29, 49, 99, 83, 53, 85, 85,  8, 43, 91, 82, 36, 82, 82, 93,
        6, 27, 26, 99, 98, 25, 59, 13, 99, 63, 99, 41, 16, 39, 73, 40, 76,
       63, 17, 31, 45, 76, 93, 83, 60, 20, 33, 20, 17, 23, 65,  3, 51, 86,
        7, 84, 11,  8,  3, 60, 47, 12,  8, 90, 51, 59, 97, 33, 63, 82, 66,
       26, 95,  3, 91, 99, 58, 29, 92,  7,  2, 16, 92, 42, 11, 53, 23, 98,
        6, 27, 25, 24, 19, 37, 54, 99,  4, 49, 88, 24, 19, 96, 82, 32, 80,
       92, 67, 45, 14, 51, 47,  4, 50, 82, 71,  3, 20, 49, 75, 65, 98, 50,
       70,  8, 88, 19, 81

### np.random.rand() : 0~1 사이의 균등분포 실수 난수를 생성한다.

In [16]:
arr = np.random.rand(10,10)
arr

array([[0.73819549, 0.49234881, 0.00498854, 0.27014285, 0.88576956,
        0.69682592, 0.56371845, 0.89142456, 0.13359325, 0.63826299],
       [0.82670931, 0.1264534 , 0.48646942, 0.94783562, 0.06272226,
        0.86153848, 0.61297483, 0.52647967, 0.96007343, 0.49161506],
       [0.33475005, 0.92494407, 0.40315541, 0.50116182, 0.61396849,
        0.72786708, 0.56118748, 0.58306194, 0.03081848, 0.10695318],
       [0.44434072, 0.4343219 , 0.95710479, 0.14960043, 0.48916723,
        0.94858916, 0.51028267, 0.66332229, 0.30661404, 0.85440801],
       [0.82509806, 0.18780086, 0.39394479, 0.8063727 , 0.51846683,
        0.75773311, 0.90860412, 0.04482851, 0.60890634, 0.2050472 ],
       [0.36526151, 0.0607862 , 0.24926532, 0.81653074, 0.08424773,
        0.39675984, 0.53410651, 0.92274741, 0.9202413 , 0.57940659],
       [0.17853672, 0.89370077, 0.80206882, 0.42788265, 0.8966387 ,
        0.51131859, 0.03057519, 0.42969205, 0.04358645, 0.52525317],
       [0.94460229, 0.88709322, 0.4412383

## seed
난수 생성의 재현성을 위해 seed 값을 고정할 수 있다.

In [17]:
np.random.seed(0)
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

## 샘플링
np.random.choice()는 기존 데이터에서 무작위로 값을 선택할 때 사용한다.
옵션
- replace=True : 복원 추출
- replace=False : 비복원 추출

In [ ]:
arr = np.array([10,3,5,7,8,9])
np.random.choice(arr)                       # 1 개 추출
np.random.choice(arr, size=3)               #추출 개수 설정
np.random.choice(arr, size=3,replace=False) # 중복 불허 비복원 추출

array([3, 5, 9])

In [38]:
# 확률 지정
probs = [0.8, 0.05, 0.05, 0.05,0.025, 0.025]
np.random.choice(arr, p=probs)

np.int64(10)