## Pytorch Tensor

## pytorch 환경 설정

In [1]:
import torch
print(torch.__version__)

2.10.0


In [2]:
# 정수형 int64 기본
# 생성 시 dtype 설정하여 실수형으로 변경

t1 = torch.tensor([1,2,3])
print(t1)
print(type(t1))
print(t1.dtype)
print(t1.shape)
print(t1.size())
print(t1.dim())   # 차원
print(t1.device)  # cpu 적재

tensor([1, 2, 3])
<class 'torch.Tensor'>
torch.int64
torch.Size([3])
torch.Size([3])
1
cpu


In [3]:
t2 = torch.tensor([[1,2,3], [4,5,6]])

print(t2)
print(type(t2))
print(t2.dtype)
print(t2.shape)
print(t2.size())
print(t2.dim())   # 차원
print(t2.device)  # cpu 적재

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
torch.int64
torch.Size([2, 3])
torch.Size([2, 3])
2
cpu


In [5]:
# 0 또는 1로 tensor 생성
print(torch.ones(2,3))  # 자료형 float32
print(torch.zeros(2,3, dtype=torch.int))

# 존대하는 tensor의 shape 를 기반으로 생성
x= torch.tensor([[1,2,3],[4,5,6]])
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [6]:
# 난수 생성
# - 정규분포 
print(torch.normal(10,1,(2,2)))    # mean, std, size
print(torch.randn((2,2)))          # size
print(torch.randn_like(x.float())) # float로 변환 후 처리

# - 균등분포
print(torch.rand((2,2)))           # size, 0~1 사이 값
print(torch.randint(1,10, (2,2)))  # start ~ stop 
print(torch.rand_like(x.float()))  # 0 ~ 1 사이 값

# - 그 외
print(torch.empty(2,3))    # 초기화 되지 않은 텐서 (쓰레기 값)

tensor([[11.0809,  8.4874],
        [ 8.7386, 10.5087]])
tensor([[-0.4073, -1.1735],
        [ 0.0102, -1.4118]])
tensor([[ 0.6261,  2.7769, -0.7486],
        [-0.8125,  0.1470, -2.1113]])
tensor([[0.3232, 0.6945],
        [0.1192, 0.4121]])
tensor([[1, 8],
        [9, 1]])
tensor([[0.8504, 0.8681, 0.1460],
        [0.1671, 0.2778, 0.2035]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# numpy ndarray 호환
import numpy as np

x = np.array([1,2,3])
print(x, type(x))

t = torch.from_numpy(x)
print(t, type(t))

x2= t.numpy()
print(x2, type(x2))

[1 2 3] <class 'numpy.ndarray'>
tensor([1, 2, 3], dtype=torch.int32) <class 'torch.Tensor'>
[1 2 3] <class 'numpy.ndarray'>


## 연산

In [8]:
a = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float)
b = torch.tensor([[7,8,9],[10,11,12]], dtype=torch.float)
c = torch.tensor([[1,2], [3,4],[5,6]], dtype=torch.float)

print(a.shape, b.shape, c.shape)

torch.Size([2, 3]) torch.Size([2, 3]) torch.Size([3, 2])


In [9]:
# 원소별 연산
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)

tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
tensor([[-6., -6., -6.],
        [-6., -6., -6.]])
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# broadcasting 연산
print(a + 1)
print(a + torch.tensor([10,20,30]))
# 마지막 축부터 확인하는데 (2,3) 과 (1,2)는 3과 2로 같지 않아 연산 불가
# print(a + torch.tensor([10,20]))

tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[11., 22., 33.],
        [14., 25., 36.]])


In [ ]:
# 내적 (모든 원소간의 곱을 더하기)
# - 1차원 : torch.dot(), torch.matmul(), @
# - 2차원 : torch.matmul(), @
m = torch.tensor([1,2,3])
n = torch.tensor([4,5,6])
print(m.dot(n))
print(torch.dot(m,n))
print(torch.matmul(m,n)) 
print(m @ n)

tensor(32)
tensor(32)
tensor(32)
tensor(32)


In [13]:
# 2차원 이상의 내적
print(a.matmul(c))   # (2,3) @ (3,2) = > (2,2)
print(a @ c)
# print(torch.dot(a,c)) -> 2차원에서 사용 불가

tensor([[22., 28.],
        [49., 64.]])
tensor([[22., 28.],
        [49., 64.]])


## 통계 연산

In [14]:
# 합계
print(torch.sum(a, dim=0))
print(torch.sum(a, dim=1))
print(torch.sum(a, dim=None))

tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor(21.)


In [15]:
# 평균
print(torch.mean(a, dim=0))
print(torch.mean(a, dim=1))
print(torch.mean(a, dim=None))

tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor(3.5000)


## 형변환

In [16]:
x = torch.tensor([1,2,3])
print(x, x.dtype)

print(x.float(), x.float().dtype)
print(x.double(), x.double().dtype)
print(x.int(), x.int().dtype)
print(x.long(), x.long().dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32
tensor([1., 2., 3.], dtype=torch.float64) torch.float64
tensor([1, 2, 3], dtype=torch.int32) torch.int32
tensor([1, 2, 3]) torch.int64


## 형태 변경

In [19]:
t = torch.arange(12)
print(t)

t_ = t.reshape(3,4)
t_ = t.reshape(3,-1)
t_ = t.reshape(-1,4)
t_ = t.reshape(2,2,3)

print(t_, t_.size())


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]) torch.Size([2, 2, 3])


In [ ]:
# 전치
t = torch.arange(12).reshape(3,4)
print(t, t.shape)
print(t.T, t.T.shape)
print(t.transpose(0,1), t.transpose(0,1).shape)  # 0차원, 1차원 교환

In [20]:
# 평탄화
print(t.flatten())
print(t.reshape(-1))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [21]:
# 차원 축소
x = torch.tensor([[[1,2], [3,4]]])
print(x.size())

print(x.squeeze(0), x.squeeze(0).shape)

torch.Size([1, 2, 2])
tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])


In [22]:
# 차원 추가
x = torch.tensor([[1,2],
                  [3,4]])
print(x.size())

x_ =x.unsqueeze(0)

print(x_,x_.size())

torch.Size([2, 2])
tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2])


## indexing | slicing

In [24]:
x =torch.arange(1,13).reshape(3,2,2)
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [25]:
# 인덱싱
print(x[0])
print(x[1,0])
print(x[2,1])
print(x[-1,-1])
print(x[-1,0,-1])

tensor([[1, 2],
        [3, 4]])
tensor([5, 6])
tensor([11, 12])
tensor([11, 12])
tensor(10)


In [ ]:
# 슬라이싱
x_ = x[:,0]    # 인덱싱 결과는 2차원
x_ = x[:,:1]   # 슬라이싱 결과는 3차원

print(x_, x_.shape)

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]) torch.Size([3, 2])


In [27]:
# fancy indexing
index = [1,2]
x_ = x[index]

print(x_, x_.shape)

tensor([[[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]) torch.Size([2, 2, 2])


## 유용한 메소드

In [28]:
# split
x = torch.zeros(10,4)
print(x)

x_splits = torch.split(x,4)

for x_ in x_splits:
    print(x_)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [30]:
# expand
k = torch.tensor([[[1,2]], [[3,4]]])
print(k, k.shape)
k_exp = k.expand(2,3,2)
print(k_exp, k_exp.shape)

tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])
tensor([[[1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4]]]) torch.Size([2, 3, 2])


In [ ]:
# 원본 배열 k의 view 형태로 k_exp가 생성 되어 k_exp가 k를 참조하고 있다
k_exp[0,0,0] = 100
print(k)
print(k_exp)

In [ ]:
# repeat
k = torch.tensor([[[1, 2]], [[3, 4]]])
print(k, k.shape)

# 차원별 반복 횟수
k_rep = k.repeat(1, 3, 1)
print(k_rep, k_rep.shape)

k_rep[0, 0, 0] = 100
print(k)
print(k_rep)

In [ ]:
# masked_fill: mask 조건식이 true 경우만 값 변경
x = torch.arange(9).reshape(3,-1)
print(x)

mask = x >4
print(mask)

x_ = x.masked_fill(mask, value=0)
print(x_)

In [ ]:
x[mask]

## 모델 학습에서 tensor 다차원 배열 연산

In [ ]:
# 단중 선형 연산
X = torch.randn(4,5)  # 연력 값: 4개의 sample, 5개의 feature
print(f'{X=}')
W = torch.randn()     # 가중치 (3개의 노드)
print(f'{W=}')
b = torch.randn(1,3)  # 노드마다 편향(bias)
print(f'b=')

# Linear 총 계산
z = torch.matmul(X, W) +b

z