# One-hot Encoding

### 1. 원-핫 인코딩이란?

단어를 벡터로 표현하는 기본 방식이다. 단어 집합 크기만큼 길이를 가진 벡터에서 해당 단어 위치만 1이고 나머지는 0으로 표현한다.

예시: `{'apple': 0, 'banana': 1, 'cherry': 2}` → `cherry` → `[0, 0, 1]`

### 2. 장점

* 직관적이고 구현이 간단하다 - 이해하기 쉽고 빠르게 적용 가능
* 수치 안정성이 뛰어나다 - 0과 1만 사용하므로 계산 오류가 적다
* 범주형 데이터에 최적화 - 순서가 없는 데이터(성별, 색상 등)를 올바르게 표현
* 실무에서 광범위하게 사용 - 표 형식 데이터 분석의 표준 방식

### 3. 한계점과 해결 방안

| 한계점             | 해결 방안                             |
| --------------- | --------------------------------- |
| 카테고리가 많으면 차원 증가 | 상위 카테고리만 선택하거나 희귀 범주 통합           |
| 의미 유사성을 반영하지 못함 | NLP는 워드 임베딩 활용, 범주형 데이터는 원-핫으로 충분 |

### 4. 언제 사용할까?

* 범주형 변수 (성별, 국가, 제품 타입)
* 카테고리가 많지 않을 때 (<50개)
* 신경망 모델 - 범주형 입력을 수치 벡터로 변환하기 위해 사용
* 선형 모델 (로지스틱 회귀, 선형 회귀) - 범주 간 순서 관계를 제거하기 위해 필요. 라벨 인코딩을 사용하면 모델이 범주를 순서가 있는 연속형 변수로 잘못 해석할 수 있다.

## one-hot encoding 예제

In [1]:
# 토큰화
from nltk.tokenize import word_tokenize

sentence = "I love NLP so much and I lova you"

tokens = word_tokenize(sentence)
print(tokens)

['I', 'love', 'NLP', 'so', 'much', 'and', 'I', 'lova', 'you']


In [2]:
# 정수 인코딩
from collections import Counter

# 단어 빈도 사전
word_counts = Counter(tokens)
print(word_counts)

# 단어 사전
word_to_index = {word : i for i, word in enumerate(word_counts)}
print(word_to_index)

# 정수 인덱스 변환
sequence = [word_to_index[word] for word in tokens]
print(sequence)

Counter({'I': 2, 'love': 1, 'NLP': 1, 'so': 1, 'much': 1, 'and': 1, 'lova': 1, 'you': 1})
{'I': 0, 'love': 1, 'NLP': 2, 'so': 3, 'much': 4, 'and': 5, 'lova': 6, 'you': 7}
[0, 1, 2, 3, 4, 5, 0, 6, 7]


In [4]:
import numpy as np
# 원핫인코딩

# 단어 사전 수, 총 클래스 수 확인
vocab_size = len(word_to_index)
print(vocab_size)

def one_hot_encoding(sequence, vocab_size):
    one_hot_vecs = []

    for seq in sequence:
        one_hot_vec = [0] * vocab_size
        one_hot_vec[seq] = 1
        one_hot_vecs.append(one_hot_vec)

    return np.array(one_hot_vec)

one_hot_vectors = one_hot_encoding(sequence, vocab_size)
print(one_hot_vectors.shape) # (문장 길이, 단어 수)
one_hot_vectors

8
(8,)


array([0, 0, 0, 0, 0, 0, 0, 1])

## 어린왕자 예제

In [5]:
# 어린왕자 샘플 텍스트
raw_text = """The Little Prince, written by Antoine de Saint-Exupéry, is a poetic tale about a young prince who travels from his home planet to Earth. The story begins with a pilot stranded in the Sahara Desert after his plane crashes. While trying to fix his plane, he meets a mysterious young boy, the Little Prince.

The Little Prince comes from a small asteroid called B-612, where he lives alone with a rose that he loves deeply. He recounts his journey to the pilot, describing his visits to several other planets. Each planet is inhabited by a different character, such as a king, a vain man, a drunkard, a businessman, a geographer, and a fox. Through these encounters, the Prince learns valuable lessons about love, responsibility, and the nature of adult behavior.

On Earth, the Little Prince meets various creatures, including a fox, who teaches him about relationships and the importance of taming, which means building ties with others. The fox's famous line, "You become responsible, forever, for what you have tamed," resonates with the Prince's feelings for his rose.

Ultimately, the Little Prince realizes that the essence of life is often invisible and can only be seen with the heart. After sharing his wisdom with the pilot, he prepares to return to his asteroid and his beloved rose. The story concludes with the pilot reflecting on the lessons learned from the Little Prince and the enduring impact of their friendship.

The narrative is a beautifully simple yet profound exploration of love, loss, and the importance of seeing beyond the surface of things."""

In [6]:
# 토큰화 + 전처리
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

sentences = sent_tokenize(raw_text)
en_stopwords = set(stopwords.words('english'))
preprocessed_sentences = []

for sent in sentences:
    tokens = word_tokenize(sent)

    tokens = [
        token.lower()
        for token in tokens
        if token.lower() not in en_stopwords
        and token.isalpha()
        and len(token) > 2
    ]

    preprocessed_sentences.append(tokens)

print(preprocessed_sentences)

[['little', 'prince', 'written', 'antoine', 'poetic', 'tale', 'young', 'prince', 'travels', 'home', 'planet', 'earth'], ['story', 'begins', 'pilot', 'stranded', 'sahara', 'desert', 'plane', 'crashes'], ['trying', 'fix', 'plane', 'meets', 'mysterious', 'young', 'boy', 'little', 'prince'], ['little', 'prince', 'comes', 'small', 'asteroid', 'called', 'lives', 'alone', 'rose', 'loves', 'deeply'], ['recounts', 'journey', 'pilot', 'describing', 'visits', 'several', 'planets'], ['planet', 'inhabited', 'different', 'character', 'king', 'vain', 'man', 'drunkard', 'businessman', 'geographer', 'fox'], ['encounters', 'prince', 'learns', 'valuable', 'lessons', 'love', 'responsibility', 'nature', 'adult', 'behavior'], ['earth', 'little', 'prince', 'meets', 'various', 'creatures', 'including', 'fox', 'teaches', 'relationships', 'importance', 'taming', 'means', 'building', 'ties', 'others'], ['fox', 'famous', 'line', 'become', 'responsible', 'forever', 'tamed', 'resonates', 'prince', 'feelings', 'rose

In [7]:
# 정수 인코딩 + 패딩
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 30
tokenizer = Tokenizer(num_words=vocab_size + 1, oov_token='OOV')
tokenizer.fit_on_texts(preprocessed_sentences)
sequences = tokenizer.texts_to_sequences(preprocessed_sentences)
print(sequences)

sequences = pad_sequences(
    sequences,
    padding='pre',
    truncating='pre',
    maxlen=16
)
print(sequences)

[[3, 2, 17, 18, 19, 20, 7, 2, 21, 22, 8, 9], [10, 23, 4, 24, 25, 26, 11, 27], [28, 29, 11, 12, 30, 7, 1, 3, 2], [3, 2, 1, 1, 13, 1, 1, 1, 5, 1, 1], [1, 1, 4, 1, 1, 1, 1], [8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6], [1, 2, 1, 1, 14, 15, 1, 1, 1, 1], [9, 3, 2, 12, 1, 1, 1, 6, 1, 1, 16, 1, 1, 1, 1, 1], [6, 1, 1, 1, 1, 1, 1, 1, 2, 1, 5], [1, 3, 2, 1, 1, 1, 1, 1, 1, 1], [1, 1, 4, 1, 1, 13, 1, 5], [10, 1, 4, 1, 14, 1, 3, 2, 1, 1, 1], [1, 1, 1, 1, 1, 1, 15, 1, 16, 1, 1, 1, 1]]
[[ 0  0  0  0  3  2 17 18 19 20  7  2 21 22  8  9]
 [ 0  0  0  0  0  0  0  0 10 23  4 24 25 26 11 27]
 [ 0  0  0  0  0  0  0 28 29 11 12 30  7  1  3  2]
 [ 0  0  0  0  0  3  2  1  1 13  1  1  1  5  1  1]
 [ 0  0  0  0  0  0  0  0  0  1  1  4  1  1  1  1]
 [ 0  0  0  0  0  8  1  1  1  1  1  1  1  1  1  6]
 [ 0  0  0  0  0  0  1  2  1  1 14 15  1  1  1  1]
 [ 9  3  2 12  1  1  1  6  1  1 16  1  1  1  1  1]
 [ 0  0  0  0  0  6  1  1  1  1  1  1  1  2  1  5]
 [ 0  0  0  0  0  0  1  3  2  1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  

In [8]:
%pip install torch

  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   --- ------------------------------------ 8.9/114.6 MB 50.6 MB/s eta 0:00:03
   ----- ---------------------------------- 17.0/114.6 MB 46.7 MB/s eta 0:00:03
   -------- ------------------------------- 23.6/114.6 MB 39.3 MB/s eta 0:00:03
   --------- ------------------------------ 28.3/114.6 MB 35.2 MB/s eta 0:00:03
   ------------ --------------------------- 37.0/114.6 MB 35.6 MB/s eta 0:00:03
   ------------- -------------------------- 39.6/114.6 MB 31.9 MB/s eta 0:00:03
   ---------------- ----------------------- 45.9/114.6 MB 31.4 MB/s eta 0:00:03
   ---------------- ----------------------- 48.2/114.6 MB 28.7 MB/s eta 0:00:03
   ------------------ --------------------- 54.3/114.6 MB 28.6 MB/s eta 0:00:03
   --------------

In [9]:
# 원핫 인코딩 변환
import torch
import torch.nn as nn 
import torch.optim as optim
import torch.nn.functional as F

# 현재 sequences의 shape : (문장 수, 문장 길이) (13,16)
X = torch.tensor(sequences, dtype=torch.long)

# 각 정수 토큰을 one-hot 벡터로 변환
# 0은 padding에 사용 되고 실제 단어 인덱스들이 그 뒤를 사용하므로 +1
input_dim = vocab_size + 1
X = F.one_hot(X, num_classes=input_dim).float()

X.shape

OSError: [WinError 127] 지정된 프로시저를 찾을 수 없습니다. Error loading "c:\Users\sunny\miniconda3\envs\dl_nlp_env\Lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

In [ ]:
# 첫 번째 문장
X[0]

## 문장 분류 예제
- 정답 데이터
 - SUMMARY : 줄거리/사건 설명
 - CHARACTER : 등장 인물 관련 설명
 - MESSAGE : 작품이 전달하는 교훈/메세지

In [ ]:
# X : 원-핫 인코딩 된 문장 데이터
# y : 각 문장의 정답 라벨
y = torch.tensor([0, 0, 0, 1, 0, 1, 2, 2, 2, 2, 0, 2, 2])

In [ ]:
# 모델 생성
# RNN 모델은 순서가 있는 데이터를 처리할 떄 자주 사용한다.
class RNNTextClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()

        self.rnn = nn.RNN(
            input_size=input_dim,    # 한 시점에 들어오는 단어 벡터 길이 (one-hot 차원 수)
            hidden_size=hidden_dim,  # RNN이 내부적으로 유지할 은닉 상태 차원 수
            batch_first=True         # 입력 shape로 (batch_size, seq_len, input_dim) 형태를 사용하도록 설정
        )

        # 마지막 은닉 상태 -> 최종 클래스 점수(logit) 반환
        self.fc = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        # output : 모든 시점의 은닉상태
        # h_n : 마지막 시점의 은닉 상태
        output, h_n = self.rnn(x)
        
        # h_n shape는 (num_layers, batch_size, hidden_dim)
        # 현재는 1층 RNN이므로 squeeze 후 (batch_size, hidden_dim) 형태로 변경하여 처리
        logits = self.fc(h_n.squeeze(0))
        return logits
    

# 입력 데이터
model = RNNTextClassifier(input_dim=input_dim=16, num_classes=3)

# 손실 함수 (다층 분류용)
criterion = nn.CrossEntropyLoss()

# 옵티마이저
optimizer = optim.Adam(model.parameters(), lr=0.005)

In [ ]:
# 모델 학습
for epoch in range(50):
    optimizer.zero_grad()

    output = model(X)

    loss = criterion(output, y)

    loss.backward()

    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch + 1} : Loss {loss.item()}')

In [ ]:
# 모델 예측
model.eval()

with torch.no_grad():
    output = model(X)
    pred = output.argmax(dim=1)         # 각 문장마다 가장 점수가 큰 클래스 번호 선택
    print('실제 라벨 : ', y.tolist())     
    print('예측 라벨 : ',  pred.tolist())